### ISSUE TITLE
pto_mg returns "Use of undeclared identifier pto_mg" 

### ISSUE THREAD

**Issue by 70uza** [harryBaker74/2915E-Programs#2]
Is anyone else having the same issues?

using pros, version 3.5.2

**Comment by harryBaker74** [comment]
I think if you click the button on the left it should work

**Comment by 70uza** [comment]
![made_you_look](https://media.tenor.com/ygz94OfGy74AAAAM/ahmed1122-ahmed1133.gif)

**Comment by harryBaker74** [comment]
???? Jouza?? or 70uza??? Unknown User

**Comment by 70uza** [comment]
oliverMun74?

**Comment by 70uza** [comment]
> I think if you click the button on the left, it should work

Hary, 

As a coder I DO NOT use a Graphical User Interface (GUI for anyone who just joined). Therefore, I am incapable of clicking any button on the left as I cannot see any physical or virtual button. Therefore, is it possible to give me a command I can use in a CLI (Command Line Interface for anyone who just joined) to solve this issue. 

I have narrowed down the issue to be something that is on the fake left.  It might also be an incorrect evaluation in the program I saw something like: 
`Left > Right` but the operator is inverted. I will not create a pull so please DIY harry. 

Thank you for your time harry.
