### ISSUE TITLE
no exit condition in calc.bat

### ISSUE THREAD

**Issue by 70uza** [harryBaker74/2915E-Programs#3]
btw calc is short for calculator

**Comment by harryBaker74** [comment]
This will be a question on the interview jordan

**Comment by 70uza** [comment]
If you're new here, calc is short for calculator.

**Comment by 70uza** [comment]
fyi calc is short for calculator.

**Comment by 70uza** [comment]
To whom this may concern, calc is short for calculator

**Comment by 70uza** [comment]
made you look

**Comment by harryBaker74** [comment]
> made you look

**Comment by 70uza** [comment]
- [x] made you look

**Comment by harryBaker74** [comment]
> * [x]  made you look

**Comment by 70uza** [comment]
Harry, for my next act i will make you look then proceed to unsubscribe from this mailing list.

**Comment by harryBaker74** [comment]
Good one
